### ISSUE TITLE
MicrosoftAccount returning sid:00000000000000000000000000000000

### ISSUE THREAD

**Issue by MartinZikmund** [Azure/azure-mobile-apps-net-server#155] opened 2016-08-10 05:43 UTC
I have not yet been able to completely isolate the issue, but trying to authenticate with Microsoft Account using `MobileServiceClient.LoginAsync` method, the app service sometimes returns a `MobileServiceUser` instance, that has `UserId`of `sid:00000000000000000000000000000000`. The interesting thing about it is that it does not happen for all accounts, some have their ID returned correctly.

**Comment by MartinZikmund** [comment] 2016-08-10 05:45
Also on the server-side, in such case the same ID is returned with:
`string userId = ( User as ClaimsPrincipal).FindFirst( ClaimTypes.NameIdentifier ).Value;`

**Comment by jamesmontemagno** [comment] 2016-08-17 01:47
have you checked out: https://github.com/Azure/azure-mobile-apps-net-server/wiki/Understanding-User-Ids with stable_id?

**Comment by adrianhall** [comment] 2016-11-02 03:11
@MartinZikmund Do you have a github repo that has a repo of this?  I can't reproduce when the MSA is configured correctly.

**Comment by adrianhall** [comment] 2016-12-05 22:47
Based on a lack of comment from the OP, closing for now.  It can be re-opened if still a problem.

**Closed by adrianhall** 2016-12-05 22:47 UTC
