### ISSUE TITLE
AccessToken is null

### ISSUE THREAD

**Issue by mlankamp** [Azure/azure-mobile-apps-net-server#59] opened 2015-12-14 14:13 UTC
I have created a new Mobile App and enabled the authentication option for Azure AD. When I use the GetAppServiceIdentityAsync to get the AzureActiveDirectoryCredentials the AccessToken is null.
How do I get the AccessToken, I need this value to request a new AccessToken for a different url?

My old App Service used a gateway where it was possible to get the AccessToken.
![accesstoken](https://cloud.githubusercontent.com/assets/8513556/11783030/2679d6a8-a275-11e5-98ea-9dc67ea08022.png)

**Comment by brettsam** [comment] 2015-12-15 20:59
This looks like a bug. It's a pretty easy fix; i should have a PR out shortly. 

The problem is that we're copying the 'access_token' value of the response to the token store, which is null. Instead, we should be looking at 'id_token' for AAD. 

If you need a workaround before we get this released, here's one way you can get this working right now -- this intercepts the response from the token store and copies 'id_token' over to 'access_token':

First, create a DelegatingHandler to copy over the value:
```
public class AadAccessTokenMessageHanlder : DelegatingHandler
{
    public AadAccessTokenMessageHanlder(HttpMessageHandler innerHandler) :
        base(innerHandler)
    {
    }

    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        HttpResponseMessage response = await base.SendAsync(request, cancellationToken);
        JObject result = await response.Content.ReadAsAsync<JObject>();
        if (result.HasValues && result["id_token"] != null && result["access_token"] == null)
        {
            result["access_token"] = result["id_token"];
            response.Content = new StringContent(result.ToString(), Encoding.UTF8, "application/json");
        }
        return response;
    }
}
```

Then create your own HttpClient and pass it to GetAppServiceIdentityAsync:
```
HttpClient httpClient = new HttpClient(new AadAccessTokenMessageHanlder(new HttpClientHandler()));
AzureActiveDirectoryCredentials aadCreds = await this.User.GetAppServiceIdentityAsync<AzureActiveDirectoryCredentials>(this.Request, httpClient);
```

**Comment by mlankamp** [comment] 2016-05-13 20:29
I just upgraded my NuGet packages from version 1.0.119.0 to 1.1.157.1 and the problem is back.

**Comment by brettsam** [comment] 2016-05-13 20:40
Were you using the workaround above?

**Comment by mlankamp** [comment] 2016-05-13 20:51
No, I wasn't. I have to use a reverse workaround:

`
if (result.HasValues && result["id_token"] == null && result["access_token"] != null)
        {
            **result["id_token"] = result["access_token"];**
            response.Content = new StringContent(result.ToString(), Encoding.UTF8, "application/json");
        }
`

**Comment by brettsam** [comment] 2016-05-13 21:05
Okay thanks -- I'm going to re-activate this issue until I can figure out what's going on.

**Comment by mlankamp** [comment] 2016-05-13 21:12
If you want me to send you the json I receive, just let me know,

**Comment by brettsam** [comment] 2016-05-16 15:25
Yeah, could you? That would help.

When I call `var creds = await this.User.GetAppServiceIdentityAsync<AzureActiveDirectoryCredentials>(this.Request);`, my `creds` has a valid `AccessToken`.

When I capture the raw JSON coming back from the request to `.auth/me`, I see: `{"id_token":"eyJ0...","provider_name":"aad","user_claims":[...],"user_id":"..."}`, which is what I would expect.

In case you aren't sure how (or for others stumbling onto this issue) -- you can issue a request to `https://{yoursite}.azurewebsites.net/.auth/me` and attach your `X-ZUMO-AUTH` token to see the data directly.

**Comment by adrianhall** [comment] 2016-11-02 03:10
@mlankamp - this is not happening for me with the latest SDKs.  Are you still having an issue?

Ref: to close 12/1/2016

**Comment by adrianhall** [comment] 2016-12-05 22:40
CLosing per 1-month closure above.

**Closed by adrianhall** 2016-12-05 22:40 UTC
