### ISSUE TITLE
IssuerClaim seems incorrect?

### ISSUE THREAD

**Issue by petergregg** [Azure/azure-mobile-apps-net-server#256] opened 2018-11-16 12:37 UTC
We are experiencing issues with the following line of code in a custom controller published in an azure mobile app service - **AzureActiveDirectoryCredentials aadCreds = await this.User.GetAppServiceIdentityAsync<AzureActiveDirectoryCredentials>(this.Request);**

We have 2 azure active directory apps one is a web/api and the other is a native application configured for the app as directed in this documentation - https://docs.microsoft.com/en-gb/azure/app-service/app-service-mobile-how-to-configure-active-directory-authentication?toc=%2fazure%2fapp-service-mobile%2ftoc.json.

We have also replicated the issue by cloning, deploying to azure and live debugging the sample app from the repo. In both instances it does work locally but once published to azure the following occurs.

The **Issuer Value** in **IPrincipalExtensions.cs** is set to **https://sts.windows.net/{tenant-id}/** - locally this is set to  
**https://{oursite}.azurewebsite.net/**

![image](https://user-images.githubusercontent.com/17479380/48621217-bffc0480-e99a-11e8-9959-ecaba903d473.png)

The summary in **AppServiceHttpClient.cs** also suggests that it should be set to **https://{oursite}.azurewebsite.net/** but it is set to **https://sts.windows.net/{tenant-id}/** 

![image](https://user-images.githubusercontent.com/17479380/48621246-d30ed480-e99a-11e8-923b-278ccbfa44c9.png)

When this line of code is executed - **HttpResponseMessage response = await this.client.SendAsync(request);** in **AppServiceHttpClient.cs** the **Response** is a 404 - Not Found as the endpoint https://sts.windows.net/{tenant-id}/.auth/me does not exist.

![image](https://user-images.githubusercontent.com/17479380/48621278-e621a480-e99a-11e8-9ba1-3d324027919e.png)

Can someone please advise if this is a code issue or an azure issue.

**Comment by ElektrojungeMS** [comment] 2018-12-05 01:11
Hey @petergregg,

Thanks for getting in touch and apologies for the delay here. Is this still happening?

Talking to various folks here, we need a little more context on which SDK you are using. Can you let me know which SDK(s) you are using and in which version? Reading through https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-convert-app-to-be-multi-tenant, it looks like either sts.windows.net or sitename.azurewebsites.com can be used as issuers depending on the scenarios. Have you checked out this doc? Maybe you can describe your scenario and give us more context on how your using which SDK?

Thanks for your patience.
Best,
Benjamin

**Comment by ElektrojungeMS** [comment] 2018-12-05 02:30
@petergregg

Before you go through all the work to answer my question above, I have one more question for you.
Did you follow every step of the setup instructions in 
https://docs.microsoft.com/en-gb/azure/app-service/app-service-mobile-how-to-configure-active-directory-authentication? It could be as simple as a setup issue.

**Comment by ElektrojungeMS** [comment] 2018-12-05 19:49
Hey!
We just ran through another set of tests using the documentation in https://docs.microsoft.com/en-gb/azure/app-service/app-service-mobile-how-to-configure-active-directory-authentication and we cannot reproduce your issue. Can you please try to integrate the SDK following the docs?

Best,
Benjamin

**Comment by petergregg** [comment] 2018-12-05 20:53
Hi Benjamin

Yes, unfortunately we are still having this issue. We have followed the documentation in  https://docs.microsoft.com/en-gb/azure/app-service/app-service-mobile-how-to-configure-active-directory-authentication and the app service authenticates/authorizes users without any issues. The above issue arises when you add a custom controller with the following line of code **AzureActiveDirectoryCredentials aadCreds = await this.User.GetAppServiceIdentityAsync(this.Request);** What is also interesting about this issue is that we have a year-old app service with a mobile backend deployed and it works fine. It seems to be new deployments of the mobile backend SDK to azure. The above snippets you see are from a cloned version of this repos SampleApp deployed into a new app service in azure with the authentication configured. Another interesting point to make is that it works fine when locally debugging. 

Many Thanks 

Peter

**Comment by petergregg** [comment] 2018-12-06 18:39
Hi Benjamin

I raised a ticket at the same time that I posted this issue but unfortunaltely no progress has been made.

Many Thanks

Peter

**Comment by ElektrojungeMS** [comment] 2018-12-06 22:56
I see. We'd real like to help you with the issue.
Is there any chance that you could send us more of your code, e.g. where/how you setup the SDK. I understand that it's probably not possible to share any here on Github, maybe you can share some privately via email. My mail is `bereimol` at microsoft dot com.

Best,
Benjamin

**Comment by ElektrojungeMS** [comment] 2018-12-12 19:43
Hey Peter,

We are following up with you through Azure support as this issue seems to be a configuration problem, I'm closing this issue here. If we find that there is an issue with the Zumo SDK here, we'll reopen the issue.

Thanks for your patience on this.

Best,
Benjamin

**Comment by guperrot** [comment] 2018-12-13 02:32
@petergregg how are you testing the login locally with the sample app?
How do you hit the SecuredController.cs file since it does not have a Route being defined?
What did you put in Web.config for AAD?
Are you using express aad settings in the portal?
What parameters did you pass in Startup.Swagger.cs line 31 for the variables to replace?

I could repo remotely by defining a custom path for SecuredController and attaching debugger to azure but I would like to see the difference with a local run and cannot figure out local authentication.

**Comment by petergregg** [comment] 2018-12-17 17:22
@guperrot sorry for the delay in getting back to you.

To test the login locally I have an aad app configured in azure as documented here - https://docs.microsoft.com/en-gb/azure/app-service/configure-authentication-provider-aad#a-nameexpress-aconfigure-azure-active-directory-using-express-settings. 

I have configured the local debugging as documented here https://github.com/Azure/azure-mobile-apps-net-server/wiki/Local-development-and-debugging-the-Mobile-App-.NET-server-backend. 

The UseDefaultConfiguration() extension method in the Startup.MobileApp.cs has the following extension method MapApiControllers() which configures the route for you, mapping any custom controllers to the /api endpoint.

I have configured swagger as documented here - https://github.com/Azure/azure-mobile-apps-net-server/wiki/Adding-Swagger-Metadata-and-Help-UI-to-a-Mobile-App

**Comment by ConnorMcMahon** [comment] 2018-12-20 19:53
@petergregg All of the issues you are seeing seems to be due to an incorrect X-ZUMO-AUTH token being passed to the application. Assuming you generated the X-ZUMO-AUTH token by hitting `https://<site-name>.azurewebsites.net/.auth/login/aad` with a POST body of `{"id_token": "<token>", "access_token": "<token>"}` (which your Native client application should be handling for you assuming it is configured correctly), that token SHOULD have an issuer of `https://<site-name>.azurewebsites.net/.auth/login/aad`. The only reason I would expect an issuer like `https://sts.windows.net/{tenant-id}/` is if your client application is passing in an AAD access token, not a zumo session token like it should be.

I would debug your client application, and make sure that it is actually grabbing the ZUMO auth token correctly. You can even grab the raw token and enter it in [](https://jwt.io) to verify the issuer is correct.

**Comment by ConnorMcMahon** [comment] 2018-12-28 23:41
@petergregg Disregard my previous comment. This is based on a regression introduced in Summer 2018.
 
Starting then, if an application has the site auth setting moduleRuntimeVersion set to any valid version >= 1.0.0, instead of populating the user Claims Principal with the claims from the X-ZUMO-AUTH token, it will populate them based on the claims in the token store (i.e. the claims from the original aad access token). This site auth setting started defaulting to "1.0.0" when turning on EasyAuth around the same time, which why we are only seeing this behavior on newer applications.
 
As a workaround, you can set "moduleRuntimeVersion" to the empty string or remove it entirely using https://resources.azure.com/. 
 
As for long term solutions, we will most likely revert the above change. We have to discuss this as a product team, as this has been out for half a year, and some customers may now depend on the new claims being present.

**Comment by jwallra** [comment] 2019-01-03 18:02
Hi @petergregg - It's been a while since we've heard from you.  Connor gave a workaround for the issue above.  I'm going to close the issue, but if you find you're still running into problems, get a hold of us and we'll give assistance.

Thanks for bringing the issue to our attention, it was a hard one to pin down!

**Closed by jwallra** 2019-01-03 18:02 UTC
Labels: Bug

**Comment by jwallra** [comment] 2019-01-14 16:45
Hi again @petergregg, we don't have any plans to make changes to this SDK based on the regression.  @ConnorMcMahon - do you guys have a public-facing issue tracking repo, UserVoice, etc.?

**Comment by ConnorMcMahon** [comment] 2019-01-14 18:56
There is a [Web Apps user voice](https://feedback.azure.com/forums/169385-web-apps), that is probably the best location.
