### ISSUE TITLE
Having the provider id encrypted in the auth token / modify token generation

### ISSUE THREAD

**Issue by PaulARoy** [Azure/azure-mobile-apps-net-server#149] opened 2016-07-24 16:30 UTC
Hi,
I am struggling right now to create a cross-provider authentication. Here I am talking about the tokens generated for providers (Fb, Tw, G+, …).

I am really close to my goal but I have a very big issue: I cannot find the provider identifier unless I make an http call, which is not possible in my code (through `GetAppServiceIdentityAsync`).

Is it not possible to encrypt the provider identifier in the token? Or to have the code to generate an sid from the provider identifier? (this could be a workaround for me)

Or even better, could we have access to the token generation? The very best thing I could do is adding a custom field to the encrypted token. That would be awesome :)

Thanks!

**Comment by brettsam** [comment] 2016-07-25 18:22
@cgillum @mattchenderson -- is there a way to get the provider id without needing to make an HTTP call?

**Comment by cgillum** [comment] 2016-07-25 20:43
Yes, you can get it from the `X-MS-CLIENT-PRINCIPAL-IDP` HTTP request header.

**Comment by PaulARoy** [comment] 2016-07-26 08:09
The idp claim only has « twitter » or « facebook » unfortunately. Same thing goes for the HTTP header.

The thing I want to get is the provider identifier, not the provider itself (something like 10153235700923123 for Facebook or 2199577123 for Twitter).

Fortunately I was able to crack down the sid encryption which means I am no longer blocked: I can use sid for authentication. My initial problem with this was the existing users on which I only kept their provider identifiers (I did not track sid).
(If you can confirm the encryption used for sid that would reassure me - I found an MD5 hash of the provider identifier with a little trick on the 16 first characters 2 by 2).

Still my question remains the same: could we access the fb/tw/g+/… token generation to add claims beforehand?

I want to create a cross-provider id and right now I have to fetch it by database / cache each time I validate the token - which is really not optimal. The best way to do this would be to add a snippet of code during the generation to hardcode this id in the token. It makes more sense at this level than at validation.

**Comment by cgillum** [comment] 2016-07-26 17:12
Oh sorry, You meant the provider's **user** identifier.

Yes, the sid was designed for identifying specific users, though there are some things to be aware of when using the sid which @brettsam has documented [here](https://github.com/Azure/azure-mobile-apps-net-server/wiki/Understanding-User-Ids).

Indeed we happen to use an MD5 hash of the provider-specific user ID to generate the SID, but I recommend you not make any assumptions about that in your application code.

Unfortunately we don't have a way of embedding custom claims into the tokens, so caching is probably your best option at this point. Adding @mattchenderson for FYI on this scenario, since I think people have asked about having a capability like this before (though we could possibly solve this more simply by adding provider claims to the zumo token like we do for browser-based cookie auth sessions).

**Comment by PaulARoy** [comment] 2016-07-27 08:53
Indeed. I messed up the terms: I was using *provider* for "facebook" and *provider identifier* for the user id on facebook. Your terms are more appropriate.

Unfortunately I have to make an assumption. I only have their provider user identifiers right now and I want to migrate into using sid (stable_sid, I read the article before of course). That again because I cannot make an HTTP call at the validation level and get the provider user identifier.

But this is a one-shot: I just create a field « sid » that I will populate on migration. After that I will save up the sid of the token and only work with tokens and sids. And I am pretty confident I retro-engineered the right algorithm based on the « understanding ids » article and a few examples.


Thanks for your answers about caching: I felt this was the best option right now even if it is not perfect.

But indeed adding claims to the token would still be the best way to do this. Where is it generated in the code? I works on another server?

**Comment by adrianhall** [comment] 2016-11-02 03:14
@PaulARoy I am going to close this one.

We have custom auth that can add custom claims to an existing JWT, that can then be used by the system.  You basically have to crack the JWT, add the claims, then re-encode.  I've got an example in my book - http://aka.ms/zumobook.

**Closed by adrianhall** 2016-11-02 03:14 UTC
Labels: App Service Authentication

**Comment by PaulARoy** [comment] 2016-11-02 08:47
Thanks for the tip.

If it can be done this bug has no value whatsoever so close it yes.
